name: django
channels:
  - conda-forge
dependencies:
  - django
  - django-environ
  - psycopg2
  - django-debug-toolbar
  - django-redis
  - protobuf
  - requests
  - pyjwt
  - pillow
  - awscli
  - django-storages
  - boto3
  - gunicorn
  - django-axes
  - pip
  - pip:
      - django-cacheops
      - django-render-block
      - django-service-urls
      - django-templated-email
      - funcy
