# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ClientLog.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'ClientLog.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x43lientLog.proto\x12\x1a\x63om.ea.simpsons.client.log\"\xdb\x04\n\x10\x43lientLogMessage\x12\x12\n\ntime_stamp\x18\x01 \x02(\x03\x12G\n\x08severity\x18\x02 \x02(\x0e\x32\x35.com.ea.simpsons.client.log.ClientLogMessage.Severity\x12\x0e\n\x06source\x18\x03 \x02(\t\x12\x0c\n\x04text\x18\x04 \x02(\t\x12\x0e\n\x06userId\x18\x05 \x01(\t\x12S\n\x0e\x63onnectionType\x18\x06 \x01(\x0e\x32;.com.ea.simpsons.client.log.ClientLogMessage.ConnectionType\x12]\n\x0fserverLogFields\x18\x07 \x01(\x0b\x32\x44.com.ea.simpsons.client.log.ClientLogMessage.ServerProvidedLogFields\x1a\xb0\x01\n\x17ServerProvidedLogFields\x12!\n\x19server_received_timestamp\x18\x01 \x01(\x03\x12!\n\x19server_received_datestamp\x18\x02 \x01(\t\x12$\n\x1cserver_received_country_code\x18\x03 \x01(\t\x12)\n!server_received_clientSessionGUID\x18\x04 \x01(\t\" \n\x08Severity\x12\x08\n\x04WARN\x10\x00\x12\n\n\x06SEVERE\x10\x01\"3\n\x0e\x43onnectionType\x12\x08\n\x04WIFI\x10\x00\x12\n\n\x06MOBILE\x10\x01\x12\x0b\n\x07UNKNOWN\x10\x02\x42!\n\x14\x63om.ea.simpsons.dataB\tClientLog')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ClientLog_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.ea.simpsons.dataB\tClientLog'
  _globals['_CLIENTLOGMESSAGE']._serialized_start=48
  _globals['_CLIENTLOGMESSAGE']._serialized_end=651
  _globals['_CLIENTLOGMESSAGE_SERVERPROVIDEDLOGFIELDS']._serialized_start=388
  _globals['_CLIENTLOGMESSAGE_SERVERPROVIDEDLOGFIELDS']._serialized_end=564
  _globals['_CLIENTLOGMESSAGE_SEVERITY']._serialized_start=566
  _globals['_CLIENTLOGMESSAGE_SEVERITY']._serialized_end=598
  _globals['_CLIENTLOGMESSAGE_CONNECTIONTYPE']._serialized_start=600
  _globals['_CLIENTLOGMESSAGE_CONNECTIONTYPE']._serialized_end=651
# @@protoc_insertion_point(module_scope)
