# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CustomerServiceData.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'CustomerServiceData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import PurchaseData_pb2 as PurchaseData__pb2
from . import LandData_pb2 as LandData__pb2
from . import Error_pb2 as Error__pb2
from . import WholeLandTokenData_pb2 as WholeLandTokenData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x43ustomerServiceData.proto\x12\x04\x44\x61ta\x1a\x12PurchaseData.proto\x1a\x0eLandData.proto\x1a\x0b\x45rror.proto\x1a\x18WholeLandTokenData.proto\"2\n\rPlayerSession\x12\x0f\n\x07ownerId\x18\x01 \x01(\t\x12\x10\n\x08hostname\x18\x02 \x01(\t\"\x7f\n\x13LandResponseMessage\x12\x1f\n\x04land\x18\x01 \x01(\x0b\x32\x11.Data.LandMessage\x12$\n\x07session\x18\x02 \x01(\x0b\x32\x13.Data.PlayerSession\x12!\n\x05\x65rror\x18\x03 \x01(\x0b\x32\x12.Data.ErrorMessage\"b\n\x17\x43urrencyResponseMessage\x12$\n\x08\x63urrency\x18\x01 \x01(\x0b\x32\x12.Data.CurrencyData\x12!\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x12.Data.ErrorMessage\"\xc6\x01\n\x13UserResponseMessage\x12\x0e\n\x06gameId\x18\x01 \x01(\t\x12@\n\x0ereverseMapping\x18\x02 \x03(\x0b\x32(.Data.UserResponseMessage.ReverseMapping\x12!\n\x05\x65rror\x18\x03 \x01(\x0b\x32\x12.Data.ErrorMessage\x1a:\n\x0eReverseMapping\x12\x12\n\nexternalId\x18\x01 \x01(\t\x12\x14\n\x0c\x65xternalType\x18\x02 \x01(\t\"\xbb\x01\n\x19LandBackupResponseMessage\x12>\n\nlandBackup\x18\x01 \x03(\x0b\x32*.Data.LandBackupResponseMessage.LandBackup\x12!\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x12.Data.ErrorMessage\x1a;\n\nLandBackup\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\x04\x12\x1f\n\x04land\x18\x02 \x01(\x0b\x32\x11.Data.LandMessage\"w\n\x1dWholeLandTokenResponseMessage\x12\x33\n\rtokenResponse\x18\x01 \x01(\x0b\x32\x1c.Data.WholeLandTokenResponse\x12!\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x12.Data.ErrorMessageB&\n$com.ea.simpsons.customerservice.data')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CustomerServiceData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.ea.simpsons.customerservice.data'
  _globals['_PLAYERSESSION']._serialized_start=110
  _globals['_PLAYERSESSION']._serialized_end=160
  _globals['_LANDRESPONSEMESSAGE']._serialized_start=162
  _globals['_LANDRESPONSEMESSAGE']._serialized_end=289
  _globals['_CURRENCYRESPONSEMESSAGE']._serialized_start=291
  _globals['_CURRENCYRESPONSEMESSAGE']._serialized_end=389
  _globals['_USERRESPONSEMESSAGE']._serialized_start=392
  _globals['_USERRESPONSEMESSAGE']._serialized_end=590
  _globals['_USERRESPONSEMESSAGE_REVERSEMAPPING']._serialized_start=532
  _globals['_USERRESPONSEMESSAGE_REVERSEMAPPING']._serialized_end=590
  _globals['_LANDBACKUPRESPONSEMESSAGE']._serialized_start=593
  _globals['_LANDBACKUPRESPONSEMESSAGE']._serialized_end=780
  _globals['_LANDBACKUPRESPONSEMESSAGE_LANDBACKUP']._serialized_start=721
  _globals['_LANDBACKUPRESPONSEMESSAGE_LANDBACKUP']._serialized_end=780
  _globals['_WHOLELANDTOKENRESPONSEMESSAGE']._serialized_start=782
  _globals['_WHOLELANDTOKENRESPONSEMESSAGE']._serialized_end=901
# @@protoc_insertion_point(module_scope)
