# Generated by Django 6.0.3 on 2026-04-28 14:33

import django.contrib.auth.models
import django.contrib.staticfiles.storage
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('is_registered', models.BooleanField(default=False)),
                ('persona_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('user_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('pid_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('telemetry_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('mayhem_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('session_key', models.CharField(max_length=44, unique=True)),
                ('donuts_balance', models.PositiveIntegerField(default=50, verbose_name='Donuts')),
                ('last_authenticated', models.DateTimeField(default=django.utils.timezone.now)),
                ('avatar', models.ImageField(blank=True, storage=django.contrib.staticfiles.storage.StaticFilesStorage(), upload_to='', verbose_name='Avatar Picture')),
                ('town', models.FileField(upload_to='./towns/', verbose_name='Town File')),
                ('events', models.BinaryField()),
                ('friends', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('advertising_id', models.UUIDField(primary_key=True, serialize=False)),
                ('device_id', models.UUIDField(unique=True)),
                ('device_id_cache', models.UUIDField(unique=True)),
                ('current_client_session_id', models.UUIDField(blank=True, null=True)),
                ('manufacturer', models.CharField(default='unknown', max_length=64)),
                ('device_model', models.CharField(default='unknown', max_length=64)),
                ('code', models.CharField(max_length=64)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('session_key', models.CharField(max_length=44, unique=True)),
                ('timestamp', models.DateTimeField(verbose_name='Token Creation/Update Time')),
                ('login_status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
