# Generated by Django 6.0 on 2026-01-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('pid_id', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(default=0)),
                ('persona_id', models.IntegerField(default=0)),
                ('mayhem_id', models.IntegerField(default=0)),
            ],
        ),
    ]
