# Generated by Django 6.0 on 2026-01-13 02:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_registered', models.BooleanField(default=False)),
                ('pid_id', models.BigIntegerField(unique=True)),
                ('user_id', models.BigIntegerField(unique=True)),
                ('persona_id', models.BigIntegerField(unique=True)),
                ('telemetry_id', models.BigIntegerField(unique=True)),
                ('mayhem_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('session_key', models.CharField(max_length=44, unique=True)),
                ('land_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('donuts_balance', models.PositiveIntegerField(default=50)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='User Date Created')),
                ('last_authenticated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Auth Date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('advertising_id', models.UUIDField(primary_key=True, serialize=False)),
                ('device_id', models.UUIDField(unique=True)),
                ('code', models.CharField(max_length=64)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('session_key', models.CharField(default='MI1cFaktxvs9pQ9UhDbI258qayqzmrkPKUsMXb4nXSk', max_length=44, unique=True)),
                ('timestamp', models.DateTimeField(verbose_name='Token Creation/Update Time')),
                ('login_status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect.userid')),
            ],
        ),
    ]
