# Generated by Django 6.0 on 2026-01-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='session_key',
            field=models.CharField(default='nvwXo_woIAAhj6LIxU9lKRTuttOUMeHR-tAk2wj6gzA', max_length=44, unique=True),
        ),
        migrations.AddField(
            model_name='userid',
            name='session_key',
            field=models.CharField(default='WTgtU712qiJ-FzPlkTo-6qBFVD1jfQoDAEIz2zs92zM', max_length=44, unique=True),
        ),
        migrations.AlterField(
            model_name='userid',
            name='is_registered',
            field=models.BooleanField(),
        ),
    ]
