# Generated by Django 6.0 on 2026-01-12 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetoken',
            name='session_key',
            field=models.CharField(default='h9DH-HxnpsGRX158biy3RQCzodpTNqIoNfGHPJwWIF4', max_length=44, unique=True),
        ),
        migrations.AlterField(
            model_name='userid',
            name='session_key',
            field=models.CharField(default='bOw0IrdU4L6Zf5qYKxJOOMSmTYLwCCTJKSbVt7TIsAI', max_length=44, unique=True),
        ),
        migrations.CreateModel(
            name='ConnectId',
            fields=[
                ('advertising_id', models.UUIDField(primary_key=True, serialize=False)),
                ('connect_id', models.UUIDField(unique=True)),
                ('login_status', models.BooleanField(default=False)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect.devicetoken')),
            ],
        ),
    ]
