# Generated by Django 6.0.3 on 2026-04-03 14:05

import django.contrib.staticfiles.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userid',
            name='avatar',
            field=models.ImageField(blank=True, storage=django.contrib.staticfiles.storage.StaticFilesStorage(), upload_to='', verbose_name='Avatar Picture'),
        ),
        migrations.AlterField(
            model_name='userid',
            name='events',
            field=models.BinaryField(),
        ),
    ]
