# Generated by Django 6.0 on 2026-01-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetoken',
            name='session_key',
            field=models.CharField(default='rmWSADHDL3GLYQtJKBUU0zLwh1BNzsp7kEV4RTiLd_Y', max_length=44, unique=True),
        ),
        migrations.AlterField(
            model_name='userid',
            name='session_key',
            field=models.CharField(default='zccVnJPjrP0hrTmss2ov_NnFIA0knoH24MqJUVR7Qf4', max_length=44, unique=True),
        ),
    ]
