# Generated by Django 6.0 on 2026-03-12 17:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userid',
            name='land_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, unique=True),
        ),
    ]
