# Generated by Django 6.0 on 2026-01-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetoken',
            name='session_key',
            field=models.CharField(default='MJ_YtQsHDqnvbJ2xlLfNFPQ1UGCdtakjs-CKeJXHKh0', max_length=44, unique=True),
        ),
    ]
