# Generated by Django 6.0 on 2026-01-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userid',
            name='friends',
            field=models.ManyToManyField(to='connect.userid'),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='session_key',
            field=models.CharField(default='vN1hJLaAG5pyaj1F5ZIpiBrmhpe63zGG4rGrnRc6CZY', max_length=44, unique=True),
        ),
    ]
