# Generated by Django 6.0.5 on 2026-05-23 23:59

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetoken',
            name='device_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='device_id_cache',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Token Creation/Update Time'),
        ),
    ]
