# Generated by Django 6.0 on 2026-01-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetoken',
            name='current_client_session_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
