# Generated by Django 6.0 on 2026-01-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_devicetoken_session_key_userid_session_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetoken',
            name='session_key',
            field=models.CharField(default='etSI28PwgCrK-DNCJV7kP8vqbO8mxdilxRQxAqp0YAg', max_length=44, unique=True),
        ),
        migrations.AlterField(
            model_name='userid',
            name='session_key',
            field=models.CharField(default='6gF_N0Ys1ClIlGLE5JkfVAiUGG6wUQi0RMQxoxSylBU', max_length=44, unique=True),
        ),
    ]
