# Generated by Django 6.0 on 2026-02-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_alter_userid_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='device_model',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
