# Generated by Django 6.0 on 2026-01-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_userid_friends_alter_devicetoken_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetoken',
            name='session_key',
            field=models.CharField(default='J2aV_Jl8U1nVlTt5_1HpQJUnoBCReWHlacS5AfoT2tM', max_length=44, unique=True),
        ),
    ]
