# Generated by Django 6.0 on 2026-03-12 17:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_alter_userid_land_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userid',
            name='land_token',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True),
        ),
    ]
