# Generated by Django 6.0 on 2026-01-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_alter_devicetoken_session_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetoken',
            name='session_key',
            field=models.CharField(default='vDAH-PRSQMufqNVT1A_ztSVNjyBBfLKzvq7INFq3bqE', max_length=44, unique=True),
        ),
        migrations.AlterField(
            model_name='userid',
            name='session_key',
            field=models.CharField(default='qSGXFxCR_kwYzd-3rjU1IJ05BZ06yxyPw1_kXkSXe14', max_length=44, unique=True),
        ),
    ]
