# Generated by Django 6.0 on 2026-01-12 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_alter_devicetoken_session_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectid',
            name='login_status',
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='login_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='session_key',
            field=models.CharField(default='DxRqwhnFoLwOGzT_T2Js37TZTP4Bh-zr3r_Gtp1LUBQ', max_length=44, unique=True),
        ),
        migrations.AlterField(
            model_name='userid',
            name='session_key',
            field=models.CharField(default='WXX3IJXuvwu1Bnk6x-CSXjcJpy-uyeR9So_TLmkTnVY', max_length=44, unique=True),
        ),
    ]
