# Generated by Django 6.1.1 on 2026-09-27 11:32

import connect.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_alter_devicetoken_device_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicetoken',
            name='session_key',
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='device_id_cache',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='Token Creation / Update Time'),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userid',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/', validators=[connect.models.validate_avatar], verbose_name='Avatar Picture'),
        ),
        migrations.AlterField(
            model_name='userid',
            name='donuts_balance',
            field=models.PositiveIntegerField(default=0, verbose_name='Donuts'),
        ),
        migrations.AlterField(
            model_name='userid',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userid',
            name='events',
            field=models.BinaryField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='userid',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userid',
            name='town',
            field=models.FileField(blank=True, upload_to='towns/', validators=[connect.models.validate_town], verbose_name='Town File'),
        ),
        migrations.AlterField(
            model_name='userid',
            name='username',
            field=models.CharField(blank=True, max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Username must be between 5 and 16 characters and contain only letters, numbers, and underscores.', regex='^[a-zA-Z0-9_]{5,16}$')]),
        ),
    ]
