# Generated by Django 6.0 on 2026-01-12 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_remove_connectid_login_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='connect_id',
            field=models.UUIDField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='session_key',
            field=models.CharField(default='mih220MIn9koOxzypPM1v0XBf-wZLapJmPfKz4JaP0I', max_length=44, unique=True),
        ),
        migrations.AlterField(
            model_name='userid',
            name='session_key',
            field=models.CharField(default='_MOvQMwrix1uvVqXZ1P-NBDDErtfsbHQE84LuieL4pU', max_length=44, unique=True),
        ),
        migrations.DeleteModel(
            name='ConnectId',
        ),
    ]
