# Generated by Django 6.0 on 2026-02-08 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_devicetoken_device_model_devicetoken_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicetoken',
            name='device_model',
        ),
        migrations.RemoveField(
            model_name='devicetoken',
            name='manufacturer',
        ),
    ]
