# Generated by Django 6.0 on 2026-03-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_alter_userid_land_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userid',
            name='session_conflict',
            field=models.BooleanField(default=False),
        ),
    ]
