# Generated by Django 6.0 on 2026-01-10 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_alter_devicetoken_session_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetoken',
            name='session_key',
            field=models.CharField(default='efB7DTdzEsk_1g070fOI1tziRcdIdy600FDebfxv6kM', max_length=44, unique=True),
        ),
        migrations.AlterField(
            model_name='userid',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userid',
            name='session_key',
            field=models.CharField(default='tVhUhgNlIGo5A750UhIC5oxYjiKXTQCkXDXHcx09eQU', max_length=44, unique=True),
        ),
    ]
