# Generated by Django 6.0 on 2026-01-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_alter_devicetoken_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetoken',
            name='session_key',
            field=models.CharField(max_length=44, unique=True),
        ),
    ]
