# Generated by Django 6.0 on 2026-03-15 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0004_userid_session_conflict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userid',
            name='land_token',
        ),
        migrations.RemoveField(
            model_name='userid',
            name='session_conflict',
        ),
    ]
