# Generated by Django 6.0 on 2026-01-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0004_devicetoken_connect_id_alter_devicetoken_session_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicetoken',
            old_name='connect_id',
            new_name='device_id',
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='session_key',
            field=models.CharField(default='oTTV8bv6HMxkQpnUQ4COl0dGQq30iMXRHmUbiomjedI', max_length=44, unique=True),
        ),
        migrations.AlterField(
            model_name='userid',
            name='session_key',
            field=models.CharField(default='7RB5qoYdGkFwQZEz0x6cuYgv84BW_pzBfoFGjFxDMDg', max_length=44, unique=True),
        ),
    ]
