# Generated by Django 6.0 on 2026-01-13 23:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0004_alter_devicetoken_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='current_client_session_id',
            field=models.UUIDField(default=uuid.UUID('fef35246-3f4c-4de8-85de-1cb696cc8b8d')),
        ),
    ]
