# Generated by Django 6.0 on 2026-02-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0004_remove_devicetoken_device_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='device_model',
            field=models.CharField(default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='manufacturer',
            field=models.CharField(default='unknown', max_length=16),
        ),
    ]
