# Generated by Django 6.0 on 2026-02-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0005_devicetoken_device_model_devicetoken_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetoken',
            name='device_model',
            field=models.CharField(default='unknown', max_length=64),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='manufacturer',
            field=models.CharField(default='unknown', max_length=64),
        ),
    ]
