# Generated by Django 6.0 on 2026-01-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0005_devicetoken_current_client_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetoken',
            name='current_client_session_id',
            field=models.UUIDField(blank=True),
        ),
    ]
