# Generated by Django 6.0 on 2026-01-13 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendinvitation',
            name='invitation_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 13, 21, 17, 43, 734037, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
