# Generated by Django 6.1.1 on 2026-09-27 11:32

import django.db.models.functions.comparison
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friendinvitation',
            name='unique_invitation_direction',
        ),
        migrations.RemoveConstraint(
            model_name='friendinvitation',
            name='unique_reverse_invitation',
        ),
        migrations.AlterField(
            model_name='friendinvitation',
            name='invitation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddConstraint(
            model_name='friendinvitation',
            constraint=models.UniqueConstraint(django.db.models.functions.comparison.Least('from_user', 'to_user'), django.db.models.functions.comparison.Greatest('from_user', 'to_user'), name='unique_bidirectional_relationship'),
        ),
    ]
