# Generated by Django 6.0 on 2026-01-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_friendinvitation_invitation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendinvitation',
            name='invitation_date',
            field=models.DateTimeField(),
        ),
    ]
