# Generated by Django 6.0 on 2026-01-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progregcode',
            name='expiry_on',
            field=models.DateTimeField(),
        ),
    ]
