# Generated by Django 6.0 on 2026-02-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progregcode',
            name='username',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
