# Generated by Django 6.0 on 2026-02-16 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progregcode',
            name='token',
        ),
    ]
