# Generated by Django 6.0 on 2026-01-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progregcode',
            name='id',
        ),
        migrations.AlterField(
            model_name='progregcode',
            name='code',
            field=models.IntegerField(default=291489),
        ),
        migrations.AlterField(
            model_name='progregcode',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
