# Generated by Django 6.0 on 2026-02-01 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
        ('proxy', '0002_progregcode_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progregcode',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connect.devicetoken'),
        ),
    ]
