# Generated by Django 6.0 on 2026-02-01 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0003_alter_progregcode_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progregcode',
            name='username',
        ),
    ]
