"""
Django settings for springfield project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import environ

# ==============================================================================
# 1. BASE & ENVIRONMENT SETUP
# ==============================================================================

BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False),
)
environ.Env.read_env(BASE_DIR / ".env")


# ==============================================================================
# 2. SECURITY & NETWORK
# ==============================================================================

DEBUG = env("DEBUG")
SECRET_KEY = env("SECRET_KEY")

SERVER_BASE_URL = env("SERVER_BASE_URL", default="http://localhost:8000").rstrip("/")

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["localhost", "127.0.0.1", "::1"])

CSRF_TRUSTED_ORIGINS = env.list(
    "CSRF_TRUSTED_ORIGINS", default=["http://localhost:8000", "http://127.0.0.1:8000"]
)

INTERNAL_IPS = env.list("INTERNAL_IPS", default=["127.0.0.1", "::1"])


# ==============================================================================
# 3. APPLICATION DEFINITION & CORE ARCHITECTURE
# ==============================================================================

CACHEOPS_REDIS = env("CACHEOPS_REDIS", default=None)

INSTALLED_APPS = [
    # Springfield Apps
    "connect.apps.ConnectConfig",
    "director.apps.DirectorConfig",
    "events.apps.EventsConfig",
    "mh.apps.MhConfig",
    "user.apps.UserConfig",
    "proxy.apps.ProxyConfig",
    "friends.apps.FriendsConfig",
    "avatar.apps.AvatarConfig",
    "dashboard.apps.DashboardConfig",
    # Django Contrib Apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-Party Apps
    "debug_toolbar",
    "axes",
    "django_cleanup.apps.CleanupConfig",
]

if CACHEOPS_REDIS:
    INSTALLED_APPS.append("cacheops")

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.gzip.GZipMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "axes.middleware.AxesMiddleware",
]

ROOT_URLCONF = "springfield.urls"
WSGI_APPLICATION = "springfield.wsgi.application"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ==============================================================================
# 4. AUTHENTICATION & USER MANAGEMENT
# ==============================================================================

AUTH_USER_MODEL = "connect.UserId"

AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",
    "django.contrib.auth.backends.ModelBackend",
]

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# ==============================================================================
# 5. SERVICE BACKENDS (DB, CACHE, STORAGE, EMAIL)
# ==============================================================================

DATABASES = {
    "default": env.db("DATABASE_URL", default=f"sqlite:///{BASE_DIR / 'database.db'}")
}

CACHES = {"default": env("CACHE_URL", default="memory://")}

STORAGES = {
    "default": env("STORAGE_DEFAULT", default="fs://?allow_overwrite=true"),
    "staticfiles": env("STORAGE_STATICFILES", default="static://"),
}

EMAIL_BACKEND = env("EMAIL_BACKEND", default="console://")


# ==============================================================================
# 6. INTERNATIONALIZATION
# ==============================================================================

LANGUAGE_CODE = "en-us"
TIME_ZONE = env("TIME_ZONE", default="UTC")
USE_I18N = True
USE_TZ = True


# ==============================================================================
# 7. STATIC & MEDIA FILES
# ==============================================================================

STATIC_URL = env("STATIC_URL", default="static/")
STATIC_ROOT = env("STATIC_ROOT", default=str(BASE_DIR / "staticfiles"))

MEDIA_URL = env("MEDIA_URL", default="media/")
MEDIA_ROOT = env("MEDIA_ROOT", default=str(BASE_DIR / "media"))


# ==============================================================================
# 8. THIRD-PARTY APP CONFIGURATIONS
# ==============================================================================

# Django-cacheops
if CACHEOPS_REDIS:
    CACHEOPS_DEGRADE_ON_FAILURE = True
    CACHEOPS = {
        "connect.*": {"ops": "all", "timeout": 60 * 60},
        "mh.*": {"ops": "all", "timeout": 60 * 60},
        "friends.*": {"ops": "all", "timeout": 60 * 60},
        "proxy.*": {"ops": "all", "timeout": 60 * 60},
    }

# Django-Axes
AXES_IPWARE_META_PRECEDENCE_ORDER = [
    "HTTP_X_FORWARDED_FOR",
    "REMOTE_ADDR",
]
AXES_FAILURE_LIMIT = env("LOGIN_ATTEMPTS", default=0)
AXES_COOLOFF_TIME = timedelta(minutes=env("LOGIN_FAIL_COOLOFF_TIME", default=30))
AXES_USE_ATTEMPT_EXPIRATION = True

if not AXES_FAILURE_LIMIT:
    AXES_ENABLED = False
