# Generated by Django 6.0 on 2026-03-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mh', '0003_alter_landtoken_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='landtoken',
            name='authorized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='landtoken',
            name='remove',
            field=models.BooleanField(default=False),
        ),
    ]
