# Generated by Django 6.0 on 2026-03-15 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mh', '0004_landtoken_authorized_landtoken_remove'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landtoken',
            name='expiry_on',
        ),
    ]
