# Generated by Django 6.0 on 2026-03-16 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mh', '0005_remove_landtoken_expiry_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landtoken',
            name='session_conflict',
        ),
    ]
