from django.http import HttpResponse, JsonResponse

# Create your views here.

def getDeviceID(request, device_id, platform):

    # Our device_id is the one generated by the director call.
    # This will be used again to associate a header called "currentClientSessionId"
    # with a device. Since most headers have underscores which are dropped by default,
    # this is the only header we can use in the mh application to identify a device.
    # We do not have access to headers such access_token and any of the sorts whose
    # contain underscores.
    response = {
        "deviceId": str(device_id),
        "resultCode": 0,
        "serverApiVersion": "1.0.0"
    }

    return JsonResponse(response)


def getAnonUid(request, device_id, platform):

    response = {
        "uid": str(device_id),
        "resultCode": 0,
        "serverApiVersion": "1.0.0",
    }

    return JsonResponse(response)


def validateDeviceID(request, device_id, platform):

    response = {
        "deviceId": str(device_id),
        "resultCode": 0,
        "serverApiVersion": "1.0.0"
    }

    return JsonResponse(response)
